### ISSUE TITLE
Wallet v1 download blocked-malware Infection

### ISSUE THREAD

**Issue by PeterMartin133** [safex/wallet#27]
Tried twice to download from official Github repository but blocked both times - pls see attached 

Any ideas please?
![SAFEXMALWARE](https://user-images.githubusercontent.com/52319498/60339660-48b33800-99a1-11e9-9afa-31bf1d4eadac.jpg)

**Comment by Kiu0612** [comment]
Thank you for reporting this issue.

We are working on getting listed so that majority of antivirus softwares does not recognize our application as malware.
For now, try whitelisting the installation file in Avast antivirus before installing the software.
Or, as a last resort, try disabling Avast antivirus until installation is complete.

**Comment by PeterMartin133** [comment]
Many thanks for your help

rgds
Peter
